name: Publish
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create Build
        run: npm install && npm run build
        
#       - name: TAR the build folder to prepare for deployment
#         run: | 
#           mkdir ../build
#           cp -TR ./build ../build
#           tar -cvf deploy.tar ../build/
          
      - name: Copy Files 
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./build"
          target: "~/ericsminiatures.com"
          overwrite: true
