name: Publish
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create Build
        run: npm install && npm run build
        
      - name: tar the build folder to prepare for deployment
        run: | 
          mkdir ../build
          cp -TR ./build ../deploy
          tar -cvf deploy.tar ../deploy/
          
      - name: Copy Files 
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./deploy.tar"
          target: "/var/www/ericsminiatures.com/html"
          overwrite: true
          rm: true
